language: node_js
node_js:
- 4.1
sudo: false
script:
- npm test
- npm run build-sample
after_success:
- npm run report-coverage

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
env:
  global:
    - CXX=g++-5
