'use strict';

var mimeToFileTypes = Object.freeze({
    'application/msword': 'MicrosoftWordDocument',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'MicrosoftWordDocument',
    'application/vnd.ms-excel': 'MicrosoftExcelDocument',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'MicrosoftExcelDocument',
    'application/vnd.ms-powerpoint': 'MicrosoftPowerpointDocument',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation': 'MicrosoftPowerpointDocument',
    'application/postscript': 'PostscriptFile',
    'application/rtf': 'RichTextFormatFile',
    'application/x-tex': 'TeXFile',
    'application/x-texinfo': 'TexinfoFile',
    'application/x-troff': 'TroffFile',
    'audio/mp3': 'MP3AudioFile',
    'audio/mp4': 'MP4AudioFile',
    'audio/basic': 'BasicAudioFile',
    'audio/x-aiff': 'AIFFAudioFile',
    'audio/x-wav': 'WavAudioFile',
    'image/bmp': 'BMPImage',
    'image/gif': 'GifImage',
    'image/ief': 'IEFImage',
    'image/x-icon': 'IconImage',
    'image/jpeg': 'JpegImage',
    'image/png': 'PNGImage',
    'image/svg+xml': 'SVGImageFile',
    'application/x-shockwave-flash': 'FlashFile',
    'image/tiff': 'TIFFImage',
    'image/x-xwindowdump': 'ScreenshotFile',
    'text/html': 'HTMLFile',
    'text/plain': 'PlainTextFile',
    'video/mpeg': 'MpegVideoFile',
    'video/ogg': 'OggVideoFile',
    'video/webm': 'WebMVideoFile',
    'video/x-flv': 'FlashVideoFile',
    'video/mp4': 'MP4VideoFile',
    'video/x-matroska': 'MatroskaVideoFile',
    'video/quicktime': 'QuicktimeVideoFile',
    'video/x-msvideo': 'MSVideoFile',
    'video/x-sgi-movie': 'MovieFile',
    'application/pdf': 'PDFFile',
    'application/zip': 'ZipFile',
    'text/css': 'CSSFile',
    'text/xml': 'XMLFile',
    'application/octet-stream': 'BinaryFile'
});

module.exports = mimeToFileTypes;
